services:
  auth-service:
    build: ./apps/auth-service
    ports:
      - "8080:8080"
    env_file:
      - ./apps/auth-service/.env

  gateway-service:
    build: ./apps/gateway-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - AUTH_SERVICE_URL=http://auth-service:8080
      - NOTES_SERVICE_URL=http://notes-service:8081
      - NODE_ENV=production
    depends_on:
      - auth-service